/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.0.0/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "hse-backend"

include(
    ":sem-2",
    ":sem-3",
    ":sem-4",
    ":sem-5",
    ":sem-7",
    ":sem-8-9:app",
)

includeBuild("sem-6")
