/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    // https://mvnrepository.com/artifact/org.jetbrains/annotations

    implementation(libs.annotations)
}
